In [1]:
print("hello world")

hello world


# Numpy

#### Numpy

Numpy stands for Numerical Python
It is a python library used for working with an arrray
Array is core component of Numpy

#### Numpy Vs List

Numpy Occupies Low Memory
Numpy is faster than List
Numpy is more flexible than list

#### Numpy Occupies Less Memory


In [2]:
import numpy as np

In [3]:
array1=np.arange(1,10,1)

In [4]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print("shape of array1 :- ",array1.shape)
print("dimension of array1 :- ",array1.ndim)
print("Type of array1 :- ",type(array1))
print("dtype of array1 :- ",array1.dtype)
print("size of array1 :- ",array1.size)
print("itemsize of array1 :- ",array1.itemsize)

shape of array1 :-  (9,)
dimension of array1 :-  1
Type of array1 :-  <class 'numpy.ndarray'>
dtype of array1 :-  int32
size of array1 :-  9
itemsize of array1 :-  4


In [6]:
print("Memory of ary1 :- ",array1.size*array1.itemsize)

Memory of ary1 :-  36


In [7]:
# List
nlist=list(range(1,10))
nlist

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
print("type of nlist :- ",type(nlist))

type of nlist :-  <class 'list'>


In [9]:
import sys
sys.getsizeof(8)

28

In [10]:
print("Memory of nlist :- ",len(nlist)*sys.getsizeof(8))

Memory of nlist :-  252


# Numpy Is Faster Than List


In [11]:
num=100000
list1=list(range(num))
list2=list(range(num))

In [13]:
#Time taken for list operation
import time
start_time=time.time()


In [15]:
reslist=[]
for x in range(100000):
    reslist.append(list1[x]+list2[x])
end_time=time.time()
print("total time:",(end_time-start_time)*10000)

total time: 366162.12606430054


In [16]:
a1=np.arange(num)
a2=np.arange(num)

In [17]:
#Time taken for Array operation
start=time.time()
res=a1+a2
end=time.time()
print(res.size)
print("time taken for array:",(end-start)*10000)

100000
time taken for array: 16.036033630371094


# Number of ways to create Numpy Array

Five ways to create Numpy Array

 Traditional Way

 Homogeneous Way

 Diagonal Way

 Numerical Way

 Random Way
 


In [18]:
import numpy as np

Traditional way

In [19]:
#Array()
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [20]:
# List to array
list1=[1,1,1,1,1]
np.array(list1)

array([1, 1, 1, 1, 1])

In [21]:
# Variables
a=np.array([12,43,26,54])
a

array([12, 43, 26, 54])

In [22]:
a.dtype

dtype('int32')

In [23]:
a.shape

(4,)

In [24]:
a.ndim

1

In [25]:
a.size

4

In [26]:
a.itemsize

4

In [27]:
a=np.array([12,43,26,54])
r=a.astype("float32")
r

array([12., 43., 26., 54.], dtype=float32)

In [28]:
r.dtype

dtype('float32')

# Homogeneous

Ones

Zeros

In [29]:
a1 = np.ones((4,4))
a1

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
ones =np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [31]:
zeros = np.zeros((3,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# Diagonal way

Eye

Identify

In [32]:
# Eye
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [33]:
np.eye(4,6,k=1)

array([[0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]])

In [35]:
# Identity
a=np.identity(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [36]:
r1=a.astype("int")
r1

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [38]:
print(r1.dtype, a.dtype)

int32 float64


In [39]:
a.itemsize

8

In [40]:
r1.itemsize

4

# 4. Numerical way

### Arrange
### linespace

In [41]:
# Arrange
a=np.arange(1,10,1)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
a.shape

(9,)

In [43]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
a.reshape(1,9)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [46]:
# Linspace
a1=np.linspace(1,10,40)
a1

array([ 1.        ,  1.23076923,  1.46153846,  1.69230769,  1.92307692,
        2.15384615,  2.38461538,  2.61538462,  2.84615385,  3.07692308,
        3.30769231,  3.53846154,  3.76923077,  4.        ,  4.23076923,
        4.46153846,  4.69230769,  4.92307692,  5.15384615,  5.38461538,
        5.61538462,  5.84615385,  6.07692308,  6.30769231,  6.53846154,
        6.76923077,  7.        ,  7.23076923,  7.46153846,  7.69230769,
        7.92307692,  8.15384615,  8.38461538,  8.61538462,  8.84615385,
        9.07692308,  9.30769231,  9.53846154,  9.76923077, 10.        ])

In [47]:
a1.shape

(40,)

In [48]:
a1.ndim

1

In [49]:
a1.size

40

In [50]:
a1.dtype

dtype('float64')

# 5. Random way

Random.rand

Random.randn

Random.randint

Random.choice



In [51]:
# 1.random.rand -- > its generates only positive float values
rand=np.random.rand(1,5)
rand

array([[0.55593711, 0.48835914, 0.90494995, 0.26924671, 0.49272494]])

In [52]:
# 2.random.randn ---> it generates positive and negative float values
randn=np.random.randn(1,10)
randn

array([[-2.57992689,  1.37575763,  1.09233314, -0.78339951, -1.98808859,
        -0.32422984,  0.75677687, -0.8563745 , -1.21165247, -0.20189906]])

In [53]:
#3.random.randint ---> it generates all positive integer values only
randint=np.random.randint(1,10,(2,4))
randint

array([[4, 3, 9, 8],
       [9, 2, 5, 6]])

In [54]:
# 4.random choice
nlist=[1,2,4,5,6]
random=np.random.choice(nlist,(3,4),p=(0.0,0.1,0.2,0.1,0.6))
random

array([[4, 6, 4, 4],
       [6, 6, 4, 6],
       [4, 4, 6, 6]])

# Multi Dimension Indexing And Slicing

# One Dimensional Array Indexing

In [55]:
import numpy as np
ary1=np.random.randint(1,40,(10))
ary1

array([18,  4, 27, 32, 12, 17, 28, 22, 28, 33])

In [56]:
ary1.shape

(10,)

In [57]:
ary1.ndim

1

In [58]:
ary1.size

10

In [59]:
ary1[3]

32

### Two Dimensional Indexing

In [60]:
ary2=np.random.randint(1,35,(4,6))
ary2

array([[15, 21,  2, 32, 31,  9],
       [18, 13,  6,  5,  2,  1],
       [22,  3, 30,  1, 27, 21],
       [22, 18,  5, 11, 19, 14]])

In [61]:
ary2[1][3]

5

#### Three Dimensional Indexing

In [62]:
ary3 = np.random.randint(10,35,(2,4,5))
ary3

array([[[15, 22, 26, 11, 13],
        [16, 13, 24, 19, 33],
        [15, 27, 30, 24, 19],
        [32, 34, 16, 14, 15]],

       [[34, 31, 20, 23, 34],
        [13, 10, 23, 11, 11],
        [24, 11, 17, 27, 24],
        [24, 26, 26, 19, 23]]])

In [63]:
ary3[1][2][3]

27

In [65]:
ary3[1][3][4]

23

### Slicing of One Dimensional Array.

In [66]:
ary1

array([18,  4, 27, 32, 12, 17, 28, 22, 28, 33])

In [68]:
len(ary1)

10

In [70]:
print(ary1[2:8:],ary1[2:8:2])

[27 32 12 17 28 22] [27 12 28]


### Slicing of Two dimensional Array

In [71]:
ary2

array([[15, 21,  2, 32, 31,  9],
       [18, 13,  6,  5,  2,  1],
       [22,  3, 30,  1, 27, 21],
       [22, 18,  5, 11, 19, 14]])

In [73]:
ary2[1:4, 1:4]

array([[13,  6,  5],
       [ 3, 30,  1],
       [18,  5, 11]])

### Slicing of Three dimensional Array.

In [74]:
ary3

array([[[15, 22, 26, 11, 13],
        [16, 13, 24, 19, 33],
        [15, 27, 30, 24, 19],
        [32, 34, 16, 14, 15]],

       [[34, 31, 20, 23, 34],
        [13, 10, 23, 11, 11],
        [24, 11, 17, 27, 24],
        [24, 26, 26, 19, 23]]])

In [75]:
ary3[1:,1:4,1:3]

array([[[10, 23],
        [11, 17],
        [26, 26]]])

# Broadcasting Rules

Case :-1 shape is same and dimension is same operation is perform on both

In [79]:
import numpy as np
a1=np.random.randint(1,20,(2,2))
a1

array([[14,  6],
       [10, 14]])

In [80]:
a2=np.random.randint(21,40,(2,2))
a2

array([[22, 32],
       [39, 22]])

In [81]:
a1+a2

array([[36, 38],
       [49, 36]])

In [82]:
print(a1.shape,a1.ndim)

(2, 2) 2


In [83]:
print(a2.shape,a2.ndim)

(2, 2) 2


# Boardcasting Rules

Case :-2 shape is different and dimensional is same


In [85]:
ary3=np.random.randint(21,40,(2,4,5))
ary3

array([[[25, 28, 38, 31, 22],
        [26, 30, 34, 35, 31],
        [39, 28, 33, 22, 28],
        [37, 28, 39, 24, 23]],

       [[37, 32, 21, 25, 38],
        [26, 34, 36, 26, 35],
        [26, 34, 26, 29, 31],
        [25, 39, 21, 29, 27]]])

In [86]:
print(ary3.shape, ary3.ndim, ary3.size)

(2, 4, 5) 3 40


In [88]:
ary4=np.random.randint(21,40,(2,4,1))
ary4

array([[[32],
        [31],
        [29],
        [33]],

       [[25],
        [37],
        [29],
        [34]]])

In [89]:
print(ary4.shape, ary4.ndim, ary4.size)

(2, 4, 1) 3 8


In [95]:
print(ary3,'\n\n\n',ary4,'\n\n\n',ary3+ary4)

[[[25 28 38 31 22]
  [26 30 34 35 31]
  [39 28 33 22 28]
  [37 28 39 24 23]]

 [[37 32 21 25 38]
  [26 34 36 26 35]
  [26 34 26 29 31]
  [25 39 21 29 27]]] 


 [[[32]
  [31]
  [29]
  [33]]

 [[25]
  [37]
  [29]
  [34]]] 


 [[[57 60 70 63 54]
  [57 61 65 66 62]
  [68 57 62 51 57]
  [70 61 72 57 56]]

 [[62 57 46 50 63]
  [63 71 73 63 72]
  [55 63 55 58 60]
  [59 73 55 63 61]]]


In [99]:
ary5=np.random.randint(21,40,(5,4))
ary5

array([[32, 38, 27, 37],
       [29, 24, 34, 28],
       [38, 23, 33, 31],
       [21, 22, 39, 27],
       [37, 30, 33, 26]])

In [100]:
print(ary5.shape, ary5.ndim, ary5.size)

(5, 4) 2 20


# Dimension different and shape aslo different


In [101]:
ary4

array([[[32],
        [31],
        [29],
        [33]],

       [[25],
        [37],
        [29],
        [34]]])

In [102]:
ary5

array([[32, 38, 27, 37],
       [29, 24, 34, 28],
       [38, 23, 33, 31],
       [21, 22, 39, 27],
       [37, 30, 33, 26]])

In [103]:
ary4+ary5

ValueError: operands could not be broadcast together with shapes (2,4,1) (5,4) 

# Boolean Indexing

In [104]:
ary1=np.random.randint(10,300,(6,10))
ary1

array([[277, 266,  56, 274,  22, 144, 156, 240, 244, 279],
       [238,  97,  40, 205,  86, 114,  55, 291, 238, 121],
       [ 54, 294, 157, 110, 169, 110, 187, 212, 124, 269],
       [ 76, 128, 269, 208, 158, 163, 122, 217,  24, 182],
       [278, 253, 230, 183,  85, 135, 165, 119, 242,  27],
       [151,  76,  14, 170, 195, 242, 234,  86, 131,  33]])

In [105]:
ary1>100

array([[ True,  True, False,  True, False,  True,  True,  True,  True,
         True],
       [ True, False, False,  True, False,  True, False,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False,  True,  True,  True,  True,  True,  True,  True, False,
         True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
        False],
       [ True, False, False,  True,  True,  True,  True, False,  True,
        False]])

In [106]:
ary1<100

array([[False, False,  True, False,  True, False, False, False, False,
        False],
       [False,  True,  True, False,  True, False,  True, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False,  True,
        False],
       [False, False, False, False,  True, False, False, False, False,
         True],
       [False,  True,  True, False, False, False, False,  True, False,
         True]])

In [107]:
ary1[ary1>100]

array([277, 266, 274, 144, 156, 240, 244, 279, 238, 205, 114, 291, 238,
       121, 294, 157, 110, 169, 110, 187, 212, 124, 269, 128, 269, 208,
       158, 163, 122, 217, 182, 278, 253, 230, 183, 135, 165, 119, 242,
       151, 170, 195, 242, 234, 131])

In [108]:
ary1[ary1<100]

array([56, 22, 97, 40, 86, 55, 54, 76, 24, 85, 27, 76, 14, 86, 33])

In [116]:
(ary1>100) & (ary1<200)

array([[False, False, False, False, False,  True,  True, False, False,
        False],
       [False, False, False, False, False,  True, False, False, False,
         True],
       [False, False,  True,  True,  True,  True,  True, False,  True,
        False],
       [False,  True, False, False,  True,  True,  True, False, False,
         True],
       [False, False, False,  True, False,  True,  True,  True, False,
        False],
       [ True, False, False,  True,  True, False, False, False,  True,
        False]])

In [114]:
ary1[(ary1>100) & (ary1<200) ]

array([144, 156, 114, 121, 157, 110, 169, 110, 187, 124, 128, 158, 163,
       122, 182, 183, 135, 165, 119, 151, 170, 195, 131])

# Np Array Transformation

1. Reshape

In [118]:
a1=np.random.randint(10,50,(20,))
a1

array([18, 26, 47, 19, 49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31,
       27, 42, 23])

In [120]:
print(a1.dtype, a1.size, type(a1), a1.shape, a1.ndim)

int32 20 <class 'numpy.ndarray'> (20,) 1


In [121]:
a1 = a1.reshape(10,2)
a1

array([[18, 26],
       [47, 19],
       [49, 19],
       [23, 25],
       [19, 13],
       [48, 27],
       [15, 24],
       [47, 27],
       [31, 27],
       [42, 23]])

In [122]:
a1 = a1.reshape(5,4)
a1

array([[18, 26, 47, 19],
       [49, 19, 23, 25],
       [19, 13, 48, 27],
       [15, 24, 47, 27],
       [31, 27, 42, 23]])

In [123]:
a1 = a1.reshape(4,5)
a1

array([[18, 26, 47, 19, 49],
       [19, 23, 25, 19, 13],
       [48, 27, 15, 24, 47],
       [27, 31, 27, 42, 23]])

In [124]:
a1 = a1.reshape(2,10)
a1

array([[18, 26, 47, 19, 49, 19, 23, 25, 19, 13],
       [48, 27, 15, 24, 47, 27, 31, 27, 42, 23]])

In [125]:
a1 = a1.reshape(2,2,5)
a1

array([[[18, 26, 47, 19, 49],
        [19, 23, 25, 19, 13]],

       [[48, 27, 15, 24, 47],
        [27, 31, 27, 42, 23]]])

In [126]:
a1 = a1.reshape(2,5,2)
a1

array([[[18, 26],
        [47, 19],
        [49, 19],
        [23, 25],
        [19, 13]],

       [[48, 27],
        [15, 24],
        [47, 27],
        [31, 27],
        [42, 23]]])

In [127]:
a1 = a1.reshape(5,2,2)
a1

array([[[18, 26],
        [47, 19]],

       [[49, 19],
        [23, 25]],

       [[19, 13],
        [48, 27]],

       [[15, 24],
        [47, 27]],

       [[31, 27],
        [42, 23]]])

# Resize

In [128]:
a1.size

20

In [130]:
a1=a1.astype("int")
a1

array([[[18, 26],
        [47, 19]],

       [[49, 19],
        [23, 25]],

       [[19, 13],
        [48, 27]],

       [[15, 24],
        [47, 27]],

       [[31, 27],
        [42, 23]]])

In [131]:
a1.resize(5,6,refcheck = False)
a1

array([[18, 26, 47, 19, 49, 19],
       [23, 25, 19, 13, 48, 27],
       [15, 24, 47, 27, 31, 27],
       [42, 23,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0]])

In [132]:
print(a1.size, a1.shape)

30 (5, 6)


In [134]:
a1=np.resize(a1,(6,8))
a1

array([[18, 26, 47, 19, 49, 19, 23, 25],
       [19, 13, 48, 27, 15, 24, 47, 27],
       [31, 27, 42, 23,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18, 26],
       [47, 19, 49, 19, 23, 25, 19, 13],
       [48, 27, 15, 24, 47, 27, 31, 27]])

In [135]:
print(a1.size, a1.shape)

48 (6, 8)


# Flatten

In [136]:
a1

array([[18, 26, 47, 19, 49, 19, 23, 25],
       [19, 13, 48, 27, 15, 24, 47, 27],
       [31, 27, 42, 23,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18, 26],
       [47, 19, 49, 19, 23, 25, 19, 13],
       [48, 27, 15, 24, 47, 27, 31, 27]])

In [137]:
a1.flatten()

array([18, 26, 47, 19, 49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31,
       27, 42, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 26, 47, 19,
       49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31, 27])

In [138]:
a1.flatten(order = "C") # Row wise order

array([18, 26, 47, 19, 49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31,
       27, 42, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 26, 47, 19,
       49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31, 27])

In [139]:
a1.flatten(order = "F") # Cloumn wise order

array([18, 19, 31,  0, 47, 48, 26, 13, 27,  0, 19, 27, 47, 48, 42,  0, 49,
       15, 19, 27, 23,  0, 19, 24, 49, 15,  0,  0, 23, 47, 19, 24,  0,  0,
       25, 27, 23, 47,  0, 18, 19, 31, 25, 27,  0, 26, 13, 27])

# Ravel

In [140]:
a1

array([[18, 26, 47, 19, 49, 19, 23, 25],
       [19, 13, 48, 27, 15, 24, 47, 27],
       [31, 27, 42, 23,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 18, 26],
       [47, 19, 49, 19, 23, 25, 19, 13],
       [48, 27, 15, 24, 47, 27, 31, 27]])

In [141]:
a1.ravel()

array([18, 26, 47, 19, 49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31,
       27, 42, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 26, 47, 19,
       49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31, 27])

In [143]:
np.ravel(a1, order = "C")

array([18, 26, 47, 19, 49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31,
       27, 42, 23,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 18, 26, 47, 19,
       49, 19, 23, 25, 19, 13, 48, 27, 15, 24, 47, 27, 31, 27])

In [144]:
np.ravel(a1, order = "F")

array([18, 19, 31,  0, 47, 48, 26, 13, 27,  0, 19, 27, 47, 48, 42,  0, 49,
       15, 19, 27, 23,  0, 19, 24, 49, 15,  0,  0, 23, 47, 19, 24,  0,  0,
       25, 27, 23, 47,  0, 18, 19, 31, 25, 27,  0, 26, 13, 27])

# Transpose

In [146]:
ary1=np.random.randint(10,50,(4,8))
ary1

array([[46, 18, 48, 19, 31, 29, 37, 42],
       [26, 27, 33, 13, 42, 22, 14, 13],
       [26, 19, 47, 48, 19, 36, 10, 35],
       [32, 35, 28, 42, 36, 23, 39, 44]])

In [147]:
print(ary1.shape, ary1.size, ary1.ndim)

(4, 8) 32 2


In [150]:
c1 = ary1.transpose()
c1

array([[46, 26, 26, 32],
       [18, 27, 19, 35],
       [48, 33, 47, 28],
       [19, 13, 48, 42],
       [31, 42, 19, 36],
       [29, 22, 36, 23],
       [37, 14, 10, 39],
       [42, 13, 35, 44]])

In [151]:
print(c1.shape, c1.size, c1.ndim)

(8, 4) 32 2


In [152]:
ary1.T

array([[46, 26, 26, 32],
       [18, 27, 19, 35],
       [48, 33, 47, 28],
       [19, 13, 48, 42],
       [31, 42, 19, 36],
       [29, 22, 36, 23],
       [37, 14, 10, 39],
       [42, 13, 35, 44]])

In [153]:
ary2=np.random.randint(10,50,(3,4,6))
ary2

array([[[28, 27, 17, 13, 18, 30],
        [15, 20, 29, 28, 38, 35],
        [32, 15, 48, 19, 47, 22],
        [20, 38, 11, 37, 30, 28]],

       [[38, 20, 20, 28, 35, 17],
        [43, 20, 11, 23, 37, 34],
        [44, 46, 45, 36, 10, 49],
        [25, 28, 16, 28, 18, 44]],

       [[18, 32, 35, 46, 22, 49],
        [28, 16, 10, 38, 24, 28],
        [10, 24, 39, 33, 18, 43],
        [23, 48, 25, 46, 44, 23]]])

In [154]:
print(ary2.shape, ary2.size, ary2.ndim)

(3, 4, 6) 72 3


In [157]:
T1  = ary2.T#reverse the shape
T1

array([[[28, 38, 18],
        [15, 43, 28],
        [32, 44, 10],
        [20, 25, 23]],

       [[27, 20, 32],
        [20, 20, 16],
        [15, 46, 24],
        [38, 28, 48]],

       [[17, 20, 35],
        [29, 11, 10],
        [48, 45, 39],
        [11, 16, 25]],

       [[13, 28, 46],
        [28, 23, 38],
        [19, 36, 33],
        [37, 28, 46]],

       [[18, 35, 22],
        [38, 37, 24],
        [47, 10, 18],
        [30, 18, 44]],

       [[30, 17, 49],
        [35, 34, 28],
        [22, 49, 43],
        [28, 44, 23]]])

In [158]:
print(T1.shape, T1.size, T1.ndim)

(6, 4, 3) 72 3


In [159]:
ary2.transpose(1,2,0)

array([[[28, 38, 18],
        [27, 20, 32],
        [17, 20, 35],
        [13, 28, 46],
        [18, 35, 22],
        [30, 17, 49]],

       [[15, 43, 28],
        [20, 20, 16],
        [29, 11, 10],
        [28, 23, 38],
        [38, 37, 24],
        [35, 34, 28]],

       [[32, 44, 10],
        [15, 46, 24],
        [48, 45, 39],
        [19, 36, 33],
        [47, 10, 18],
        [22, 49, 43]],

       [[20, 25, 23],
        [38, 28, 48],
        [11, 16, 25],
        [37, 28, 46],
        [30, 18, 44],
        [28, 44, 23]]])

In [160]:
ary2.transpose(1,2,0).shape

(4, 6, 3)

In [161]:
ary2.shape

(3, 4, 6)

In [168]:
ary3=np.random.randint(10,50,(2,3,5,6))
ary3

array([[[[36, 24, 30, 28, 36, 19],
         [40, 36, 21, 38, 19, 42],
         [42, 41, 31, 32, 21, 14],
         [23, 12, 26, 42, 46, 47],
         [23, 27, 41, 40, 27, 43]],

        [[35, 33, 18, 33, 46, 42],
         [38, 36, 17, 44, 22, 47],
         [33, 12, 26, 43, 16, 48],
         [40, 33, 35, 15, 24, 49],
         [24, 30, 48, 28, 36, 24]],

        [[25, 46, 26, 28, 43, 17],
         [12, 20, 32, 21, 18, 30],
         [17, 10, 34, 26, 49, 18],
         [49, 38, 45, 46, 28, 16],
         [26, 46, 31, 14, 10, 39]]],


       [[[34, 30, 11, 31, 24, 29],
         [46, 27, 30, 35, 34, 29],
         [17, 38, 38, 34, 24, 10],
         [30, 44, 14, 49, 15, 43],
         [15, 32, 13, 28, 25, 21]],

        [[38, 30, 29, 17, 18, 43],
         [46, 11, 13, 33, 44, 37],
         [46, 46, 28, 36, 34, 21],
         [31, 47, 45, 41, 35, 16],
         [18, 35, 38, 41, 13, 10]],

        [[31, 13, 43, 44, 44, 25],
         [41, 36, 28, 34, 25, 12],
         [37, 30, 32, 15, 22, 48],
        

In [169]:
ary3.transpose(2,0,3,1)

array([[[[36, 35, 25],
         [24, 33, 46],
         [30, 18, 26],
         [28, 33, 28],
         [36, 46, 43],
         [19, 42, 17]],

        [[34, 38, 31],
         [30, 30, 13],
         [11, 29, 43],
         [31, 17, 44],
         [24, 18, 44],
         [29, 43, 25]]],


       [[[40, 38, 12],
         [36, 36, 20],
         [21, 17, 32],
         [38, 44, 21],
         [19, 22, 18],
         [42, 47, 30]],

        [[46, 46, 41],
         [27, 11, 36],
         [30, 13, 28],
         [35, 33, 34],
         [34, 44, 25],
         [29, 37, 12]]],


       [[[42, 33, 17],
         [41, 12, 10],
         [31, 26, 34],
         [32, 43, 26],
         [21, 16, 49],
         [14, 48, 18]],

        [[17, 46, 37],
         [38, 46, 30],
         [38, 28, 32],
         [34, 36, 15],
         [24, 34, 22],
         [10, 21, 48]]],


       [[[23, 40, 49],
         [12, 33, 38],
         [26, 35, 45],
         [42, 15, 46],
         [46, 24, 28],
         [47, 49, 16]],

        [[30, 

In [170]:
ary3.transpose(2,0,3,1).shape

(5, 2, 6, 3)

# 6. Swap Axes

In [162]:
b1=np.random.randint(10,60,(4,5))
b1

array([[14, 43, 30, 41, 12],
       [29, 18, 54, 54, 25],
       [35, 55, 20, 46, 26],
       [57, 49, 53, 22, 20]])

In [163]:
b1.shape

(4, 5)

In [164]:
b1.swapaxes(1,0)

array([[14, 29, 35, 57],
       [43, 18, 55, 49],
       [30, 54, 20, 53],
       [41, 54, 46, 22],
       [12, 25, 26, 20]])

In [165]:
b1.swapaxes(1,0).shape

(5, 4)

In [171]:
ary3

array([[[[36, 24, 30, 28, 36, 19],
         [40, 36, 21, 38, 19, 42],
         [42, 41, 31, 32, 21, 14],
         [23, 12, 26, 42, 46, 47],
         [23, 27, 41, 40, 27, 43]],

        [[35, 33, 18, 33, 46, 42],
         [38, 36, 17, 44, 22, 47],
         [33, 12, 26, 43, 16, 48],
         [40, 33, 35, 15, 24, 49],
         [24, 30, 48, 28, 36, 24]],

        [[25, 46, 26, 28, 43, 17],
         [12, 20, 32, 21, 18, 30],
         [17, 10, 34, 26, 49, 18],
         [49, 38, 45, 46, 28, 16],
         [26, 46, 31, 14, 10, 39]]],


       [[[34, 30, 11, 31, 24, 29],
         [46, 27, 30, 35, 34, 29],
         [17, 38, 38, 34, 24, 10],
         [30, 44, 14, 49, 15, 43],
         [15, 32, 13, 28, 25, 21]],

        [[38, 30, 29, 17, 18, 43],
         [46, 11, 13, 33, 44, 37],
         [46, 46, 28, 36, 34, 21],
         [31, 47, 45, 41, 35, 16],
         [18, 35, 38, 41, 13, 10]],

        [[31, 13, 43, 44, 44, 25],
         [41, 36, 28, 34, 25, 12],
         [37, 30, 32, 15, 22, 48],
        

In [172]:
ary3.shape

(2, 3, 5, 6)

In [173]:
ary3.swapaxes(1,0).shape

(3, 2, 5, 6)

# 7. Flip

In [174]:
b1

array([[14, 43, 30, 41, 12],
       [29, 18, 54, 54, 25],
       [35, 55, 20, 46, 26],
       [57, 49, 53, 22, 20]])

In [175]:
print(b1.shape, b1.size, b1.ndim)

(4, 5) 20 2


In [176]:
np.flip(b1)

array([[20, 22, 53, 49, 57],
       [26, 46, 20, 55, 35],
       [25, 54, 54, 18, 29],
       [12, 41, 30, 43, 14]])

In [177]:
np.fliplr(b1)

array([[12, 41, 30, 43, 14],
       [25, 54, 54, 18, 29],
       [26, 46, 20, 55, 35],
       [20, 22, 53, 49, 57]])

In [178]:
np.flipud(b1)

array([[57, 49, 53, 22, 20],
       [35, 55, 20, 46, 26],
       [29, 18, 54, 54, 25],
       [14, 43, 30, 41, 12]])

In [179]:
np.flip(b1,axis=0)

array([[57, 49, 53, 22, 20],
       [35, 55, 20, 46, 26],
       [29, 18, 54, 54, 25],
       [14, 43, 30, 41, 12]])

In [180]:
np.flip(b1,axis=1)

array([[12, 41, 30, 43, 14],
       [25, 54, 54, 18, 29],
       [26, 46, 20, 55, 35],
       [20, 22, 53, 49, 57]])

# Numpy - Functions

np.Where()

In [181]:
a=100
b=200
np.where(a>=b ,a,b)

array(200)

In [182]:
x=150
y=250
z=425
np.where((x>=y)&(x>=z),x,(np.where((y<z),z,y)))

array(425)

In [184]:
ary1=np.random.randint(10,50,(8,))
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [185]:
ary2=np.random.randint(10,35,(8,))
ary2

array([25, 32, 20, 20, 27, 22, 15, 16])

In [186]:
np.where(ary1>ary2,ary1,ary2)

array([42, 32, 47, 20, 27, 38, 41, 30])

# ArgMax & ArgMin


In [187]:
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [188]:
np.argmax(ary1)

2

In [189]:
np.argmin(ary1)

3

In [192]:
a=np.random.randint(10,50,(4,6))
a

array([[19, 20, 48, 12, 19, 39],
       [47, 25, 27, 44, 19, 44],
       [33, 17, 24, 48, 41, 11],
       [24, 19, 40, 11, 28, 18]])

In [193]:
np.argmax(a)

2

In [194]:
np.argmin(a)

17

In [195]:
np.argmax(a,axis=0) # columns wise

array([1, 1, 0, 2, 2, 1], dtype=int64)

In [196]:
np.argmin(a,axis=1) # Row  wise

array([3, 4, 5, 3], dtype=int64)

In [197]:
np.argmin(a)

17

In [198]:
np.argmin(a,axis=0)

array([0, 2, 2, 3, 0, 2], dtype=int64)

In [199]:
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [200]:
print(np.max(ary1), np.min(ary1), np.argmax(ary1), np.argmin(ary1))

47 15 2 3


In [202]:
dir(np)

['ALLOW_THREADS',
 'BUFSIZE',
 'CLIP',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__former_attrs__',
 '__future_scalars__',
 '__getattr__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_add_newdoc_ufunc',
 '_builtins',
 '_distributor_init',
 '_financi

In [209]:
# help(np.mod)

Help on ufunc:

remainder = <ufunc 'remainder'>
    remainder(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

    Returns the element-wise remainder of division.

    Computes the remainder complementary to the `floor_divide` function.  It is
    equivalent to the Python modulus operator``x1 % x2`` and has the same sign
    as the divisor `x2`. The MATLAB function equivalent to ``np.remainder``
    is ``mod``.

    .. warning::

        This should not be confused with:

        * Python 3.7's `math.remainder` and C's ``remainder``, which
          computes the IEEE remainder, which are the complement to
          ``round(x1 / x2)``.
        * The MATLAB ``rem`` function and or the C ``%`` operator which is the
          complement to ``int(x1 / x2)``.

    Parameters
    ----------
    x1 : array_like
        Dividend array.
    x2 : array_like
        Divisor array.
        If ``x1.shape != x2.shape``, they must be bro

In [208]:
print(np.mean(ary1), np.median(ary1), np.std(ary1))

32.875 34.0 10.361436917725262


#### for mode there is no method in Numerical Python, but it is scipy , so we have use that libray, for that First we have to install that library first.


In [213]:
# pip install scipy

In [212]:
from scipy import stats


In [215]:
# Mode
mode_result = stats.mode(ary1)


In [217]:
mode_value = mode_result.mode[0]
# mode_count = mode_result.count[0]
# print(f"Mode: {mode_value} (appeared {mode_count} times)")

IndexError: invalid index to scalar variable.

In [216]:
mode_result

ModeResult(mode=15, count=1)

In [218]:
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [221]:
np.unique(ary1)

array([15, 21, 29, 30, 38, 41, 42, 47])

In [227]:
# Get unique elements and their counts
unique_elements, counts = np.unique(ary1, return_counts=True)
print(unique_elements,counts)

# Find the index of the maximum count
max_count_index = np.argmax(counts)
print(max_count_index)

# The mode value(s)
mode_value = unique_elements[max_count_index]
mode_count = counts[max_count_index]

print(f"Mode: {mode_value} (appeared {mode_count} times)", max_count_index)



[15 21 29 30 38 41 42 47] [1 1 1 1 1 1 1 1]
0
Mode: 15 (appeared 1 times) 0


Diag  in page number 31

# Diag - page number 31

In [228]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [229]:
np.diag(np.arange(3,6))

array([[3, 0, 0],
       [0, 4, 0],
       [0, 0, 5]])

In [230]:
np.diag([3,4,5,6])

array([[3, 0, 0, 0],
       [0, 4, 0, 0],
       [0, 0, 5, 0],
       [0, 0, 0, 6]])

In [231]:
np.diag(np.arange(1,6))

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

# Full 

In [232]:
np.full((5),9)

array([9, 9, 9, 9, 9])

In [233]:
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

# Repeat

In [234]:
np.repeat([10,20,30,40],3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30, 40, 40, 40])

#  Seed

In [235]:
np.random.randint(10,20,(4,5))

array([[16, 12, 12, 19, 18],
       [16, 16, 19, 16, 16],
       [19, 13, 16, 18, 12],
       [11, 16, 15, 16, 13]])

In [236]:
np.random.seed(0)
np.random.randint(10,20,(3,3))

array([[15, 10, 13],
       [13, 17, 19],
       [13, 15, 12]])

In [237]:
b1=np.array([[10,20],[40,50]])
b1

array([[10, 20],
       [40, 50]])

In [238]:
m1=np.matrix([[12,23],[10,45]])
m1

matrix([[12, 23],
        [10, 45]])

In [239]:
print(type(m1), type(b1))

<class 'numpy.matrix'> <class 'numpy.ndarray'>


In [240]:
m2=np.matrix("3,4 ; 5,6")
m2

matrix([[3, 4],
        [5, 6]])

In [241]:
m3=np.matrix("2,4;3,5")
m3

matrix([[2, 4],
        [3, 5]])

In [242]:
m2*m3

matrix([[18, 32],
        [28, 50]])

# Determinant

In [243]:
# Create a 2x2 matrix
a1=np.random.randint(4,10,(2,2))
# Calculate the determinant
# det(matrix)=(a * d) -(b * c)
determinant = np.linalg.det(a1)
# Display the result
print("Matrix 2x2:")
print(a1)
print("Determinant:", determinant)

Matrix 2x2:
[[8 4]
 [4 8]]
Determinant: 47.999999999999986


In [244]:
b=np.random.randint(2,8,(3,3))
b

array([[4, 3, 2],
       [3, 7, 3],
       [7, 2, 3]])

In [245]:
np.linalg.det(b)

9.999999999999998

# Round

In [246]:
n=50.494342189

In [247]:
np.round(n)

50.0

In [248]:
np.round(n,2)

50.49

# ABS

In [249]:
n1=np.array([[1,-2,4],[-6,4,-2]])
n1

array([[ 1, -2,  4],
       [-6,  4, -2]])

In [250]:
np.abs(n1)

array([[1, 2, 4],
       [6, 4, 2]])

# Expand_dims

In [251]:
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [252]:
ary1.ndim

1

In [253]:
x=np.expand_dims(ary1,axis=0)
x

array([[42, 29, 47, 15, 21, 38, 41, 30]])

In [254]:
x.ndim

2

In [255]:
x.shape

(1, 8)

In [256]:
n=np.expand_dims(ary1,axis=1)
n

array([[42],
       [29],
       [47],
       [15],
       [21],
       [38],
       [41],
       [30]])

In [257]:
n.ndim

2

In [259]:
n.shape

(8, 1)

# Squeeze

In [260]:
n

array([[42],
       [29],
       [47],
       [15],
       [21],
       [38],
       [41],
       [30]])

In [261]:
np.squeeze(n)

array([42, 29, 47, 15, 21, 38, 41, 30])

# Count Non-Zero

In [262]:
z=np.random.randint(0,5,(10))
z

array([4, 3, 0, 3, 0, 2, 3, 0, 1, 3])

In [263]:
np.count_nonzero(z)

7

# Sort

In [264]:
ary1

array([42, 29, 47, 15, 21, 38, 41, 30])

In [265]:
np.sort(ary1) # forascendingorder

array([15, 21, 29, 30, 38, 41, 42, 47])

In [267]:
np.sort(ary1)[::-1]

array([47, 42, 41, 38, 30, 29, 21, 15])